### ISSUE TITLE
Security by default

### ISSUE THREAD

**Issue by jgreat** [jgreat/trireme#8]
Enterprise users want to know that their clusters are following best practices. Creating a K8s cluster is not easy, there are a ton of options to consider. Use CIS Benchmark recommend options as a place to start.

Good Defaults, Clear documentation of security options. Make

Things that should be implemented, but flexible. 
* PodSecurityPolicy - Even if the default is Unrestricted, it should be enabled and available. 
* NetworkPolicy - Use network provider that support network policy
* Audit Logs
* EventRateLimits
* AlwaysPullImages - Optional
* Secrets Encryption
* SSL Certificate generation and Rotation.

Make the cluster configs template-able so the can be reused.

**Comment by chrisgundersen** [comment]
Useful links:

[The Kubernetes Bench for Security is a Go application that checks whether Kubernetes is deployed according to security best practices](https://github.com/aquasecurity/kube-bench)

[CIS Benchmarks for Kubernetes](https://www.cisecurity.org/benchmark/kubernetes/)
